// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: pb/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreDeductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreDeductRequest) Reset() {
	*x = PreDeductRequest{}
	mi := &file_pb_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreDeductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreDeductRequest) ProtoMessage() {}

func (x *PreDeductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreDeductRequest.ProtoReflect.Descriptor instead.
func (*PreDeductRequest) Descriptor() ([]byte, []int) {
	return file_pb_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *PreDeductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PreDeductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PreDeductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreDeductResponse) Reset() {
	*x = PreDeductResponse{}
	mi := &file_pb_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreDeductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreDeductResponse) ProtoMessage() {}

func (x *PreDeductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreDeductResponse.ProtoReflect.Descriptor instead.
func (*PreDeductResponse) Descriptor() ([]byte, []int) {
	return file_pb_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *PreDeductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PreDeductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RollbackDeductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackDeductRequest) Reset() {
	*x = RollbackDeductRequest{}
	mi := &file_pb_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackDeductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackDeductRequest) ProtoMessage() {}

func (x *RollbackDeductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackDeductRequest.ProtoReflect.Descriptor instead.
func (*RollbackDeductRequest) Descriptor() ([]byte, []int) {
	return file_pb_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackDeductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RollbackDeductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RollbackDeductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackDeductResponse) Reset() {
	*x = RollbackDeductResponse{}
	mi := &file_pb_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackDeductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackDeductResponse) ProtoMessage() {}

func (x *RollbackDeductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackDeductResponse.ProtoReflect.Descriptor instead.
func (*RollbackDeductResponse) Descriptor() ([]byte, []int) {
	return file_pb_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackDeductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackDeductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_inventory_proto protoreflect.FileDescriptor

const file_pb_inventory_proto_rawDesc = "" +
	"\n" +
	"\x12pb/inventory.proto\x12\tinventory\"M\n" +
	"\x10PreDeductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"G\n" +
	"\x11PreDeductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x15RollbackDeductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"L\n" +
	"\x16RollbackDeductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb1\x01\n" +
	"\x10InventoryService\x12F\n" +
	"\tPreDeduct\x12\x1b.inventory.PreDeductRequest\x1a\x1c.inventory.PreDeductResponse\x12U\n" +
	"\x0eRollbackDeduct\x12 .inventory.RollbackDeductRequest\x1a!.inventory.RollbackDeductResponseB\x0eZ\fpb/inventoryb\x06proto3"

var (
	file_pb_inventory_proto_rawDescOnce sync.Once
	file_pb_inventory_proto_rawDescData []byte
)

func file_pb_inventory_proto_rawDescGZIP() []byte {
	file_pb_inventory_proto_rawDescOnce.Do(func() {
		file_pb_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_inventory_proto_rawDesc), len(file_pb_inventory_proto_rawDesc)))
	})
	return file_pb_inventory_proto_rawDescData
}

var file_pb_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_inventory_proto_goTypes = []any{
	(*PreDeductRequest)(nil),       // 0: inventory.PreDeductRequest
	(*PreDeductResponse)(nil),      // 1: inventory.PreDeductResponse
	(*RollbackDeductRequest)(nil),  // 2: inventory.RollbackDeductRequest
	(*RollbackDeductResponse)(nil), // 3: inventory.RollbackDeductResponse
}
var file_pb_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.InventoryService.PreDeduct:input_type -> inventory.PreDeductRequest
	2, // 1: inventory.InventoryService.RollbackDeduct:input_type -> inventory.RollbackDeductRequest
	1, // 2: inventory.InventoryService.PreDeduct:output_type -> inventory.PreDeductResponse
	3, // 3: inventory.InventoryService.RollbackDeduct:output_type -> inventory.RollbackDeductResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_inventory_proto_init() }
func file_pb_inventory_proto_init() {
	if File_pb_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_inventory_proto_rawDesc), len(file_pb_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_inventory_proto_goTypes,
		DependencyIndexes: file_pb_inventory_proto_depIdxs,
		MessageInfos:      file_pb_inventory_proto_msgTypes,
	}.Build()
	File_pb_inventory_proto = out.File
	file_pb_inventory_proto_goTypes = nil
	file_pb_inventory_proto_depIdxs = nil
}
